apiVersion: apps/v1
kind: Deployment

metadata:
  name: python
spec:
  selector:
      matchLabels:
        app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      initContainers:
        - name: verify-redis-dns
          image: busybox
          command: ['sh', '-c', "until nslookup redis-master.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo redis-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
        - name: verify-redis-ready
          image: busybox
          command: ['sh', '-c', "until echo -e 'PING' | nc -w1 redis-master.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 6379; do echo redis-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
      
      containers:
        - name: lab3
          image: lab3
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15